#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sat Jul 22 22:17:38 2017

@author: yufan
"""

import tensorflow as tf

g1 = tf.Graph()
with g1.as_default():
    # Init variable "v" in graph g1, and give value 0
    v = tf.get_variable(
            "v", initializer=tf.zeros_initializer(), shape=[1])

g2 = tf.Graph()
with g2.as_default():
    # Init variable "v" in graph g2, and give value 1
    v = tf.get_variable(
            "v", initializer=tf.ones_initializer(), shape=[1])
    
# Read variable "v" in g1
with tf.Session(graph=g1) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        # Because we are in graph g1, the variable v should be 0
        print sess.run( tf.get_variable("v") )
    
# Read variable "v" in g2
with tf.Session(graph=g2) as sess:
    tf.global_variables_initializer().run()
    with tf.variable_scope("", reuse=True):
        # Because we are in graph g2, the variable v should be 1
        print sess.run( tf.get_variable("v") )
    