#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Sat Jul 22 22:33:34 2017

@author: yufan
"""

import tensorflow as tf

g = tf.Graph()
# Specify the GPU for running
with g.device('/gpu:0'):
    a = tf.constant(1.0)
    b = tf.constant(2.0)
    result = a + bccc